import { Player } from './types';

// Mock data for fallback when API is unavailable
export const mockPlayers: Player[] = [
  {
    id: "1",
    name: "Romarinho",
    age: 34,
    position: "Right Winger",
    nationality: "Brazilian",
    club: "Fenerbahçe",
    marketValue: "€12.5M",
    isLbPlayer: true,
  },
  {
    id: "2",
    name: "Uilton",
    age: 32,
    position: "Right Winger",
    nationality: "Brazilian",
    club: "FC Porto",
    marketValue: "€8.2M",
  },
  {
    id: "3",
    name: "Tiago Orobó",
    age: 31,
    position: "Center-Forward",
    nationality: "Brazilian",
    club: "Barcelona",
    marketValue: "€15.7M",
    isLbPlayer: true,
  },
  {
    id: "4",
    name: "Buller",
    age: 30,
    position: "Left Winger",
    nationality: "Brazilian",
    club: "Manchester United",
    marketValue: "€7.3M",
  },
  {
    id: "5",
    name: "Farley Rosa",
    age: 31,
    position: "Left Winger",
    nationality: "Brazilian / Portuguese",
    club: "FC Porto",
    marketValue: "€9.1M",
    isLbPlayer: true,
  },
  {
    id: "6",
    name: "Lucas Rocha",
    age: 29,
    position: "Center-Back",
    nationality: "Brazilian",
    club: "AC Milan",
    marketValue: "€11.8M",
  },
  {
    id: "7",
    name: "Paulo Henrique",
    age: 26,
    position: "Defensive Midfielder",
    nationality: "Brazilian",
    club: "Juventus",
    marketValue: "€14.2M",
    isLbPlayer: true,
  },
];
